name: Run Postman Tests

on:
  pull_request:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Укажите вашу версию Java
          distribution: 'adopt'

      - name: Build and run server
        run: |
          cd later # Укажите правильный путь к вашему проекту
          ./mvnw spring-boot:run & # Запускаем сервер в фоновом режиме
          sleep 30 # Ждем, пока сервер запустится

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run postman_tests/Sprint_14_ShareItadd-controllers.postman_collection.json